<?xml version="1.0" ?>

<!DOCTYPE studentRecord [
	<!ELEMENT studentRecord (studentNumber, firstName, lastName, result)>
	<!ELEMENT studentNumber (#PCDATA)>
	<!ELEMENT firstName (#PCDATA)>
	<!ELEMENT lastName (#PCDATA)>
	<!ELEMENT result (subject*)>
	<!ELEMENT subject (code, creditPoint, mark, grade)>
	<!ELEMENT code (#PCDATA)>
	<!ELEMENT creditPoint (#PCDATA)>
	<!ELEMENT mark (#PCDATA)>
	<!ELEMENT grade (#PCDATA)>
]>

<studentRecord>
	<studentNumber>1231234</studentNumber>
	<firstName>John</firstName>
	<lastName>Smith</lastName>
	<email>jsmith@gmail.com</email>
	<result>
		<subject>
			<code>MATH101</code>
			<creditPoint>4</creditPoint>
			<mark>85</mark>
			<grade>A</grade>
		</subject>
		<subject>
			<code>ECON111</code>
			<creditPoint>5</creditPoint>
			<mark>70</mark>
			<grade>B</grade>
		</subject>
		<subject>
			<code>CS100</code>
			<creditPoint>5</creditPoint>
			<mark>80</mark>
			<grade>A</grade>
		</subject>
		<subject>
			<code>LAW121</code>
			<creditPoint>6</creditPoint>
			<mark>75</mark>
			<grade>N</grade>
		</subject>
	</result>
</studentRecord>